### ISSUE TITLE
Phase 2: Community volunteers opt in as group managers

### ISSUE THREAD

**Issue by jcleblanc** [DevRel-Foundation/governance#74]
**Description**
Using the final list of key themes from Phase 1, volunteers from the community will opt-in to manage the group responsible for a theme. (Duration: 10 Days)

- Limit of 1 group selection per person.
- Minimum of 2 hours per week commitment.
- Minimum of 6 months commitment.
- Minimum of 3 managers for each group.

**Output**
- List of community group managers

**Supporting Documents**
- [Phased Plan](https://github.com/DevRel-Foundation/governance/blob/main/drf_phases_plan.md)

**Comment by goofmint** [comment]
Thanks!

If I need clarification on something, please point it out.

- A group consists of 3 managers (Minimum. NO double-hatting)
- A group consists of 8 members (Minimum. Double-hatting is allowed)

In other words, a working group consists of at least 11 people (8 people can belong to multiple groups).

**Comment by wesley83** [comment]
@goofmint I believe your assessment is correct. Those are the minimum amounts of people per group. We don't have any upper bounds defined, and if groups don't obtain those minimum numbers, they will not move forward in the process.

**Comment by jcleblanc** [comment]
Closing issues associated with deprecated project plan. Please see https://github.com/orgs/DevRel-Foundation/projects/7 for new project plan
